name: Release NPM packages

on:
  workflow_dispatch:
    inputs:
      release:
        description: Version type to publish
        required: true
        type: choice
        options: [major, minor, patch]

jobs:
  npm:
    uses: akromio/github/.github/workflows/nodejs-release.yaml@master
    with:
      release: ${{ inputs.release }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
